### ISSUE TITLE
Resources for bigpipe itself not including subdomain path

### ISSUE THREAD

**Issue by runruh** [bigpipe/plugin-domain#1]
The js and css resources delivered for bigpipe itself when using extern are not including the subdirectory specified in the path, the pagelets work fine. Looking at the repo it looks as if only the pagelet compiler is adjusted.

**Comment by Swaagie** [comment]
Are this your CSS/JS resources or the generated extern library, anyways lets discuss this in slack, probably will be faster :) Was on holiday the last week

**Comment by Swaagie** [comment]
Fixed with #15
